services:
    db:
        image: postgres:16
        container_name: dev_postgres
        environment:
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=dev_pass
            - POSTGRES_DB=dev
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata: