DROP TABLE IF EXISTS user_resources;
DROP TABLE IF EXISTS user_idles;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS idles;
DROP TABLE IF EXISTS resources;
DROP TABLE IF EXISTS skills;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(500) NOT NULL UNIQUE,
    password VARCHAR(500) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    jti UUID NOT NULL UNIQUE,           -- Store the unique token ID (jti)
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    revoked BOOLEAN DEFAULT FALSE
);


CREATE TABLE IF NOT EXISTS skills (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS resources (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    skill INTEGER REFERENCES skills(id)
);

CREATE TABLE IF NOT EXISTS idles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    resource INTEGER REFERENCES resources(id),
    skill INTEGER REFERENCES skills(id),
    level INTEGER NOT NULL 
);

CREATE TABLE IF NOT EXISTS user_idles (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    started TIMESTAMP DEFAULT NULL,
    active BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS user_resources (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    count INTEGER DEFAULT 0
);